name: CI Checks

on:
  pull_request:
    branches: [dev, main]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform validate (dev)
        run: |
          cd terraform/dev
          terraform init -backend=false
          terraform validate
<<<<<<< HEAD
=======

      - name: Terraform validate (prod)
        run: |
          cd terraform/prod
          terraform init -backend=false
          terraform validate
>>>>>>> 58f06da (fixed terraform setup on ci)
